### ISSUE TITLE
Only one signature object is attached to document

### ISSUE THREAD

**Issue by tbssdc** [aaron-hardin/ParallelApproval#2]
So I ran a doc through the workflow with two approvers, and upon the second approval, the Signature Object of the first approval is replaced with the second Signature. I'm open to using the signature manifestation function instead, but it was my impression that will always be updated with each new manifestation.

Previously we had multiple signature objects attached to a document as it went though the workflow. How can we get that with this new workflow? Is it that there can only be one sig object associated with the state transition of PendApprove->ContentApproved?

**Comment by aaron-hardin** [comment]
This will need to be handled by changing the Identifier on the signature that has just been signed.

The document has a field called Signatures that points to the newly created Signature object right?

**Comment by tbssdc** [comment]
Yep, either Signature(s) or Signature Manifestation.

**Comment by aaron-hardin** [comment]
Okay, in that case. In the State Action script, we can get the signature object and change the identifier.

Can you get me the alias for the Identifier property (or whatever it is called on the Signature object), the alias of the Signatures property, and the alias of the Signature object?
If there is not an alias on one of those just let me know and I will give you an alias to put.

**Comment by tbssdc** [comment]
Alias ID Property is `M-Files.QMS.Signature.Title`
Property is `Files.QMS.Signatures`
For class is `Files.QMS.Signature.Class.Executed`

**Comment by aaron-hardin** [comment]
Do you have a property with alias <code>M-Files.QMS.Signature.Identifier</code>?
It should be called "Signature Identifier"
You should also have a property User Account <code>M-Files.QMS.UserAccount</code>

**Comment by tbssdc** [comment]
Yes to both, they are both present.

On Thu, Feb 26, 2015 at 12:33 PM, aaron-hardin notifications@github.com
wrote:

> Do you have a property with alias M-Files.QMS.Signature.Identifier?
> It should be called "Signature Identifier"
> You should also have a property User Account M-Files.QMS.UserAccount
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aaron-hardin/ParallelApproval/issues/2#issuecomment-76264749
> .

## 

Tyler Bradford, Ops Engineering and Support (Contractor)
_SweetSpot Diabetes Care_, a Dexcom Company
tbradford@sweetspotdiabetes.com

http://www.SweetSpotDiabetes.com http://www.sweetspotdiabetes.com/
cell: _971-563-2273_ | fax: 503-227-5272

---

CONFIDENTIALITY NOTICE:
This electronic transmission, and any documents attached hereto, may
contain confidential and/or privileged information. The information is
intended only for use by the recipient named above. If you are not the
named addressee, you are not authorized to read, print, retain, copy or
disseminate this message or any part of it. If you have received this
electronic message in error, please notify the sender and delete the
electronic message. Any disclosure, copying, distribution, or use of the
contents of information received in error is strictly prohibited.

## 

---

CONFIDENTIALITY NOTICE:
This electronic transmission, and any documents attached hereto, may 
contain confidential and/or privileged information. The information is 
intended only for use by the recipient named above. If you are not the 
named addressee, you are not authorized to read, print, retain, copy or 
disseminate this message or any part of it. If you have received this 
electronic message in error, please notify the sender and delete the 
electronic message. Any disclosure, copying, distribution, or use of the 
contents of information received in error is strictly prohibited.

**Comment by aaron-hardin** [comment]
This one is ready for testing, please install the new script and let me know if there are any issues with it.

**Comment by tbssdc** [comment]
Additions of commit [7eb085](https://github.com/aaron-hardin/ParallelApproval/commit/7eb08589291fdd689607ed561a6da5377b473a84) work like a charm. Nice job, many thanks.
