### ISSUE TITLE
(M-Files Server) is listed in the Approved By PropVal

### ISSUE THREAD

**Issue by tbssdc** [aaron-hardin/ParallelApproval#3]
After the final approval, (M-Files Server) is added to the Approved By Property. Not a huge deal, but would be nice if it wasn't there, as it would make it look like we are allowing a system to do automatic review of quality documents to an auditor.

**Comment by aaron-hardin** [comment]
This can be fixed, I will make an update later today.

**Comment by aaron-hardin** [comment]
' Example usage: Dim updated : Set updated = SetLastModifiedBy(ObjVer, CurrentUserID.Value)
' Example usage: Call SetLastModifiedBy(ObjVer, CurrentUserID.Value)
Function SetLastModifiedBy(obj, lastModifiedByUser)
    ' Set who modified object last
    ' obj is an ObjVer
    ' lastModifiedByUser is userId
    ' returns ObjectVersionAndProperties
    Dim tvLastUser : Set tvLastUser = CreateObject("MFilesAPI.TypedValue")
    tvLastUser.SetValue 9, lastModifiedByUser

```
Dim tvTime : Set tvTime = CreateObject("MFilesAPI.TypedValue")

Set SetLastModifiedBy = Vault.ObjectPropertyOperations.SetLastModificationInfoAdmin(obj, True, tvLastUser, False, tvTime)
```

End Function

**Comment by aaron-hardin** [comment]
This fix has been applied, please test.

**Comment by tbssdc** [comment]
Commit [30195e9](https://github.com/aaron-hardin/ParallelApproval/commit/30195e98742313722c203e4528f9a247e8e60a3c) did the trick, thanks.
